version: '3.8'

services:
  app:
    # KLUCZOWA ZMIANA:
    # Wskazujemy folder 'backend' jako kontekst.
    # Docker automatycznie poszuka tam pliku 'Dockerfile' i 'requirements.txt'
    build: ./backend

    container_name: fin_assistant_app
    ports:
      - "8000:8000"
    volumes:
      # Mapujemy kod backendu (żeby zmiany w Pythonie działały od razu)
      - ./backend:/app
      # Mapujemy frontend (jako pliki statyczne)
      - ./frontend:/frontend

    # Plik .env przenieśliśmy do backendu, więc wskazujemy go tutaj:
    env_file:
      - ./backend/.env

    environment:
      - PYTHONUNBUFFERED=1