version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fin_assistant_app
    ports:
      - "8000:8000"
    volumes:
      # Mapowanie kodu backendu (zmiany widoczne od razu)
      - ./backend:/app
      # Mapowanie kodu frontendu
      - ./frontend:/app/static
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1